import React,{useEffect,useState}from'react';import{createRoot}from'react-dom/client';import'./style.css';
const API=import.meta.env.VITE_API_URL||'http://localhost:4000';
const euro=c=>(Number(c)/100).toLocaleString('de-DE',{style:'currency',currency:'EUR'});
async function call(path,opt={},token=''){const r=await fetch(API+path,{...opt,headers:{'Content-Type':'application/json',...(token?{Authorization:`Bearer ${token}`}:{})}});const d=await r.json();if(!r.ok)throw new Error(d.error||'Fehler');return d}
function App(){const[token,setToken]=useState(localStorage.getItem('token')||''),[user,setUser]=useState(null),[drinks,setDrinks]=useState([]),[bookings,setBookings]=useState([]),[members,setMembers]=useState([]),[ledger,setLedger]=useState([]),[dash,setDash]=useState(null),[page,setPage]=useState('cash');
useEffect(()=>{if(token)load(token)},[]);
async function load(t=token){try{const me=await call('/api/auth/me',{},t);setUser(me);setDrinks(await call('/api/drinks',{},t));setBookings(await call('/api/drinks/my-bookings',{},t));if(me.role==='admin'){setMembers(await call('/api/admin/users',{},t));setDash(await call('/api/admin/dashboard',{},t));setLedger(await call('/api/admin/ledger',{},t));}}catch{logout()}}
async function login(u,p){try{const d=await call('/api/auth/login',{method:'POST',body:JSON.stringify({username:u,password:p})});localStorage.setItem('token',d.token);setToken(d.token);await load(d.token)}catch(e){alert(e.message)}}
async function buy(id){try{await call('/api/drinks/buy/'+id,{method:'POST'},token);await load()}catch(e){alert(e.message)}}
async function topup(id,amount){try{await call('/api/admin/topup',{method:'POST',body:JSON.stringify({userId:id,amountCents:Math.round(Number(amount)*100)})},token);await load()}catch(e){alert(e.message)}}
function logout(){localStorage.removeItem('token');setToken('');setUser(null)}
if(!user)return <Login login={login}/>;
return <main className="app"><header><div className="logo">∞</div><h1>AD INFINITUM</h1><p>Ride · Brotherhood · Respect</p></header><section className="card gold"><h2>Hallo {user.name}</h2><span className="badge">{user.memberNumber} · {user.role}</span><p>Guthaben</p><div className="balance">{euro(user.balanceCents)}</div></section><nav>{['cash','history',...(user.role==='admin'?['admin']:[])].map(x=><button className={page===x?'active':''}onClick={()=>setPage(x)}key={x}>{x==='cash'?'ClubCash':x==='history'?'Buchungen':'Admin'}</button>)}</nav>{page==='cash'&&drinks.map(d=><div className="card drink"key={d.id}><span>{d.emoji}</span><div><b>{d.name}</b><br/>{euro(d.price_cents)}<br/><small>Bestand: {d.stock}</small></div><button onClick={()=>buy(d.id)}>+</button></div>)}{page==='history'&&bookings.map(b=><div className="card"key={b.id}><b>{b.drinkName}</b><br/>{euro(b.priceCents)}<br/><small>{new Date(b.createdAt).toLocaleString('de-DE')}</small></div>)}{page==='admin'&&<Admin members={members}ledger={ledger}dash={dash}topup={topup}/>}<button className="secondary"onClick={logout}>Abmelden</button></main>}
function Login({login}){const[u,setU]=useState('florian'),[p,setP]=useState('club123');return <main className="app"><header><div className="logo">∞</div><h1>AD INFINITUM</h1></header><section className="card gold"><input value={u}onChange={e=>setU(e.target.value)}placeholder="Benutzername"/><input value={p}onChange={e=>setP(e.target.value)}type="password"placeholder="Passwort"/><button onClick={()=>login(u,p)}>Einloggen</button></section></main>}
function Admin({members,ledger,dash,topup}){const[a,setA]=useState({});return <section><h2>Adminbereich</h2>{dash&&<div className="grid"><div className="tile">Mitglieder<br/><b>{dash.members}</b></div><div className="tile">Guthaben<br/><b>{euro(dash.totalBalanceCents)}</b></div><div className="tile">Verkauft<br/><b>{dash.sold}</b></div><div className="tile">Lagerwarnungen<br/><b>{dash.lowStock.length}</b></div></div>}<h3>Guthaben</h3>{members.filter(m=>m.role==='member').map(m=><div className="card"key={m.id}><b>{m.name}</b><br/><small>{euro(m.balanceCents)}</small><input value={a[m.id]||''}onChange={e=>setA({...a,[m.id]:e.target.value})}placeholder="Euro"/><button onClick={()=>topup(m.id,a[m.id])}>Freigeben</button></div>)}<h3>Protokoll</h3>{ledger.slice(0,20).map(x=><div className="card"key={x.id}><b>{x.member_name}</b><br/>{x.type} · {euro(x.amount_cents)}<br/><small>{new Date(x.created_at).toLocaleString('de-DE')}</small></div>)}</section>}
createRoot(document.getElementById('root')).render(<App/>);
