import React,{useEffect,useState}from'react';import{createRoot}from'react-dom/client';import'./style.css';
const API=import.meta.env.VITE_API_URL||'http://localhost:4000';const euro=c=>(Number(c)/100).toLocaleString('de-DE',{style:'currency',currency:'EUR'});
async function call(p,o={},t=''){const r=await fetch(API+p,{...o,headers:{'Content-Type':'application/json',...(t?{Authorization:`Bearer ${t}`}:{})}});const d=await r.json();if(!r.ok)throw new Error(d.error||'Fehler');return d}
function App(){const[token,setToken]=useState(localStorage.getItem('token')||''),[user,setUser]=useState(null),[drinks,setDrinks]=useState([]),[bookings,setBookings]=useState([]),[topups,setTopups]=useState([]),[open,setOpen]=useState([]),[members,setMembers]=useState([]),[page,setPage]=useState('cash');
useEffect(()=>{if(token)load(token)},[]);
async function load(t=token){try{const me=await call('/api/auth/me',{},t);setUser(me);setDrinks(await call('/api/drinks',{},t));setBookings(await call('/api/drinks/mine',{},t));setTopups(await call('/api/topups/mine',{},t));if(me.role==='admin'){setOpen(await call('/api/admin/topups',{},t));setMembers(await call('/api/admin/users',{},t));}}catch{logout()}}
async function login(u,p){try{const d=await call('/api/auth/login',{method:'POST',body:JSON.stringify({username:u,password:p})});localStorage.setItem('token',d.token);setToken(d.token);await load(d.token)}catch(e){alert(e.message)}}
async function buy(id){try{await call('/api/drinks/buy/'+id,{method:'POST'},token);await load()}catch(e){alert(e.message)}}
async function request(amount){try{await call('/api/topups',{method:'POST',body:JSON.stringify({amountCents:Math.round(Number(amount)*100)})},token);await load()}catch(e){alert(e.message)}}
async function approve(id){await call('/api/admin/topups/'+id+'/approve',{method:'POST'},token);await load()}
async function reject(id){await call('/api/admin/topups/'+id+'/reject',{method:'POST'},token);await load()}
async function addMember(m){try{await call('/api/admin/users',{method:'POST',body:JSON.stringify(m)},token);await load()}catch(e){alert(e.message)}}
function logout(){localStorage.removeItem('token');setToken('');setUser(null)}
if(!user)return <Login login={login}/>;
return <main><header><div>∞</div><h1>AD INFINITUM</h1></header><section className="gold"><h2>{user.name}</h2><p>{user.memberNumber}</p><strong>{euro(user.balanceCents)}</strong></section><nav><button onClick={()=>setPage('cash')}>ClubCash</button><button onClick={()=>setPage('history')}>Historie</button>{user.role==='admin'&&<button onClick={()=>setPage('admin')}>Admin</button>}</nav>{page==='cash'&&<><section>{drinks.map(d=><article key={d.id}><span>{d.emoji}</span><div><b>{d.name}</b><br/>{euro(d.price_cents)}<br/><small>Bestand {d.stock}</small></div><button onClick={()=>buy(d.id)}>+</button></article>)}</section><Topup request={request}topups={topups}/></>}{page==='history'&&bookings.map(b=><article key={b.id}><b>{b.drink_name}</b><br/>{euro(b.price_cents)}</article>)}{page==='admin'&&<Admin open={open}members={members}approve={approve}reject={reject}addMember={addMember}/>}<button onClick={logout}>Abmelden</button></main>}
function Login({login}){const[u,setU]=useState('florian'),[p,setP]=useState('club123');return <main><header><div>∞</div><h1>AD INFINITUM</h1></header><section className="gold"><input value={u}onChange={e=>setU(e.target.value)}/><input type="password"value={p}onChange={e=>setP(e.target.value)}/><button onClick={()=>login(u,p)}>Einloggen</button></section></main>}
function Topup({request,topups}){const[a,setA]=useState('');return <section className="gold"><h3>Guthaben anfragen</h3><input value={a}onChange={e=>setA(e.target.value)}placeholder="Euro"/><button onClick={()=>request(a)}>Senden</button>{topups.map(t=><p key={t.id}>{euro(t.amount_cents)} · {t.status}</p>)}</section>}
function Admin({open,members,approve,reject,addMember}){const[m,setM]=useState({username:'',name:'',password:''});return <section><section className="gold"><h3>Mitglied anlegen</h3><input placeholder="Benutzername"onChange={e=>setM({...m,username:e.target.value})}/><input placeholder="Name"onChange={e=>setM({...m,name:e.target.value})}/><input placeholder="Passwort"onChange={e=>setM({...m,password:e.target.value})}/><button onClick={()=>addMember(m)}>Anlegen</button></section><h3>Offene Anfragen</h3>{open.map(x=><article key={x.id}><b>{x.member_name}</b><br/>{euro(x.amount_cents)}<button onClick={()=>approve(x.id)}>Freigeben</button><button onClick={()=>reject(x.id)}>Ablehnen</button></article>)}<h3>Mitglieder</h3>{members.map(x=><article key={x.id}><b>{x.name}</b><br/>{x.username}</article>)}</section>}
createRoot(document.getElementById('root')).render(<App/>);
