
const initial={current:null,page:"home",cashTab:"drinks",adminTab:"stats",users:{florian:{password:"club123",name:"Florian",role:"member",balance:24.50,bookings:[],bike:"Harley-Davidson Street Bob",memberNo:"AI-001",joined:"2026",active:true,points:120},admin:{password:"admin123",name:"Admin",role:"admin",balance:0,bookings:[],bike:"Ad Infinitum Verwaltung",memberNo:"AI-000",joined:"2026",active:true,points:999}},members:["florian"],topupRequests:[],drinks:[{name:"Augustiner",price:2,stock:18,min:20,emoji:"🍺",sold:0},{name:"Chiemseer",price:2,stock:76,min:20,emoji:"🍺",sold:0},{name:"Monster Energy",price:2.5,stock:9,min:10,emoji:"🟢",sold:0},{name:"Red Bull",price:2,stock:41,min:10,emoji:"🔴",sold:0},{name:"Kaffee",price:2,stock:28,min:8,emoji:"☕",sold:0},{name:"Wasser",price:1,stock:53,min:20,emoji:"💧",sold:0},{name:"Cola 250 ml",price:1.5,stock:63,min:20,emoji:"🥤",sold:0},{name:"Fanta 250 ml",price:1.5,stock:44,min:20,emoji:"🥤",sold:0},{name:"Sprite 250 ml",price:1.5,stock:38,min:20,emoji:"🥤",sold:0}],chat:[{from:"Admin",text:"Willkommen im Ad Infinitum Club-Chat.",time:"Heute 18:00",pinned:true}],events:[{title:"Clubabend",date:"Samstag, 19:00 Uhr",place:"Clubhaus",rsvp:["Florian"]},{title:"Saison-Ausfahrt",date:"Sonntag, 10:00 Uhr",place:"Treffpunkt Clubhaus",rsvp:[]}],tours:[{title:"Saison-Ausfahrt",duration:"2 Stunden",via:"Bad Tölz · Tegernsee · Sylvenstein",style:"Kurvig & landschaftlich",riders:["Florian"],route:"Clubhaus → Bad Tölz → Tegernsee → Sylvenstein → Clubhaus"}],ledger:[],cashClosings:[]};
let state=JSON.parse(localStorage.getItem("adInfinitumClubAppV07")||JSON.stringify(initial));const app=document.getElementById("app");const save=()=>localStorage.setItem("adInfinitumClubAppV07",JSON.stringify(state));const euro=n=>Number(n).toLocaleString("de-DE",{style:"currency",currency:"EUR"});const now=()=>new Date().toLocaleString("de-DE");
function hero(){return `<div class="hero"><div class="infinity"></div><h1>AD INFINITUM</h1><p>Ride · Brotherhood · Respect</p></div>`}
function loginScreen(msg=""){app.innerHTML=`<div class="app">${hero()}<div class="card gold"><h2>Anmelden</h2>${msg?`<p class="warn">${msg}</p>`:""}<input id="username" placeholder="Benutzername"><input id="password" placeholder="Passwort" type="password"><button onclick="login()">Einloggen</button><p class="small">Demo: florian / club123 · admin / admin123</p></div></div>`}
function login(){const u=document.getElementById("username").value.trim().toLowerCase();const p=document.getElementById("password").value;if(state.users[u]&&state.users[u].password===p&&state.users[u].active){state.current=u;state.page="home";save();render()}else loginScreen("Benutzername oder Passwort falsch oder Mitglied deaktiviert.")}
function nav(){const admin=state.users[state.current].role==="admin";const items=[["home","🏠","Start"],["cash","🍺","Cash"],["chat","💬","Chat"],["tours","🗺️","Touren"],[admin?"admin":"profile",admin?"👑":"👤",admin?"Admin":"Profil"]];return `<div class="nav">${items.map(i=>`<button class="${state.page===i[0]?'active':''}" onclick="state.page='${i[0]}';save();render()">${i[1]}<br>${i[2]}</button>`).join("")}</div>`}
function render(){if(!state.current)return loginScreen();if(state.page==="cash")return cash();if(state.page==="chat")return chat();if(state.page==="tours")return tours();if(state.page==="admin")return admin();if(state.page==="profile")return profile();if(state.page==="events")return events();if(state.page==="install")return install();return home()}
function home(){const u=state.users[state.current],low=state.drinks.filter(d=>d.stock<d.min).length;app.innerHTML=`<div class="app">${hero()}<div class="card gold"><h2>Hallo ${u.name} 👋</h2><span class="badge">${u.memberNo} · ${u.points} Clubpunkte</span><p>Dein Guthaben</p><div class="balance">${euro(u.balance)}</div>${u.balance<5?`<p class="warn">Bitte bald Guthaben aufladen.</p>`:`<p class="ok">Guthaben aktiv</p>`}</div><div class="grid"><div class="tile" onclick="state.page='cash';render()">🍺<b>ClubCash</b><span class="small">Getränke buchen</span></div><div class="tile" onclick="state.page='chat';render()">💬<b>Chat</b><span class="small">${state.chat.length} Nachrichten</span></div><div class="tile" onclick="state.page='tours';render()">🗺️<b>Touren</b><span class="small">${state.tours.length} geplant</span></div><div class="tile" onclick="state.page='events';render()">📅<b>Events</b><span class="small">${state.events.length} Termine</span></div></div>${low?`<div class="card"><h3 class="warn">Lagerwarnung</h3><p>${low} Getränke unter Mindestbestand.</p></div>`:""}${nav()}</div>`}
function cash(){const u=state.users[state.current];app.innerHTML=`<div class="app"><h2>ClubCash</h2><div class="card gold"><p>Guthaben</p><div class="balance">${euro(u.balance)}</div></div><div class="tabs"><button class="${state.cashTab==='drinks'?'active':''}" onclick="state.cashTab='drinks';cash()">Getränke</button><button class="${state.cashTab==='history'?'active':''}" onclick="state.cashTab='history';cash()">Historie</button></div>${state.cashTab==='drinks'?drinkList()+topupBox():historyList()}${nav()}</div>`}
function topupBox(){return `<div class="card"><h3>Guthaben anfragen</h3><p class="small">Für Barzahlung oder Überweisung. Admin muss freigeben.</p><input id="topup" type="number" step="0.01" placeholder="Betrag, z. B. 20"><button class="secondary" onclick="requestTopup()">Anfrage senden</button></div>`}
function requestTopup(){const amount=Number(document.getElementById("topup").value||0);if(amount<=0)return alert("Betrag eingeben.");state.topupRequests.unshift({member:state.current,name:state.users[state.current].name,amount,time:now(),status:"offen"});save();alert("Guthaben-Anfrage gesendet.");cash()}
function drinkList(){return state.drinks.map((d,i)=>`<div class="card drink"><div class="emoji">${d.emoji}</div><div class="info"><b>${d.name}</b><br><span style="color:var(--gold)">${euro(d.price)}</span> <span class="small">· Bestand: ${d.stock}</span>${d.stock<d.min?`<br><span class="warn">Niedrig</span>`:""}</div><button onclick="buy(${i})">+</button></div>`).join("")}
function historyList(){const u=state.users[state.current];return `<div class="card"><h3>Meine Buchungen</h3>${u.bookings.length?u.bookings.map(b=>`<p class="msg"><b>${b.drink}</b> · ${euro(b.price)}<br><span class="small">${b.time}</span></p>`).join(""):`<p class="small">Noch keine Buchungen.</p>`}</div>`}
function buy(i){const u=state.users[state.current],d=state.drinks[i];if(d.stock<=0)return alert("Nicht auf Lager.");if(u.balance<d.price)return alert("Nicht genügend Guthaben.");d.stock--;d.sold=(d.sold||0)+1;u.balance=+(u.balance-d.price).toFixed(2);u.points+=1;const entry={drink:d.name,price:d.price,time:now()};u.bookings.unshift(entry);state.ledger.unshift({type:"Getränk",member:u.name,amount:-d.price,item:d.name,time:entry.time,admin:"System"});save();alert(`${d.name} gebucht. Neues Guthaben: ${euro(u.balance)}`);cash()}
function chat(){const pinned=state.chat.filter(m=>m.pinned),normal=state.chat.filter(m=>!m.pinned);app.innerHTML=`<div class="app"><h2>Club-Chat</h2>${pinned.map(m=>`<div class="card gold"><b>📌 ${m.from}</b><p>${m.text}</p><span class="small">${m.time}</span></div>`).join("")}${normal.map(m=>`<div class="card"><b>${m.from}</b><br><p>${m.text}</p><span class="small">${m.time}</span></div>`).join("")}<div class="card"><input id="chatText" placeholder="Nachricht schreiben..."><button onclick="sendChat()">Senden</button>${state.users[state.current].role==="admin"?`<button class="secondary" onclick="sendAnnouncement()">Als Ankündigung anheften</button>`:""}</div>${nav()}</div>`}
function sendChat(){const text=document.getElementById("chatText").value.trim();if(!text)return;state.chat.push({from:state.users[state.current].name,text,time:now(),pinned:false});save();chat()}
function sendAnnouncement(){const text=document.getElementById("chatText").value.trim();if(!text)return;state.chat.unshift({from:"Vorstand",text,time:now(),pinned:true});save();chat()}
function tours(){app.innerHTML=`<div class="app"><h2>Tourenplaner</h2><div class="mapbox">🗺️ Routenvorschau<br><span class="small">Demo: Aus Orten wird eine Tour-Reihenfolge erstellt</span></div><div class="card gold"><h3>Route erstellen</h3><input id="tourTitle" placeholder="Name der Tour"><input id="tourDuration" placeholder="Fahrzeit, z. B. 1 Stunde"><textarea id="tourVia" rows="3" placeholder="Über welche Städte?"></textarea><select id="tourStyle"><option>Kurvig & landschaftlich</option><option>Schnellste Route</option><option>Rundtour</option></select><button onclick="generateRoute()">Routenvorschlag erstellen</button></div><div class="card"><h3>Geplante Touren</h3>${state.tours.map((t,i)=>`<p class="msg"><b>${t.title}</b><br><span class="small">${t.duration} · ${t.style}</span><br>${t.route||t.via}<br><span class="small">Teilnehmer: ${t.riders?.join(", ")||"keine"}</span><br><button class="secondary" onclick="joinTour(${i})">Teilnehmen</button><button class="secondary" onclick="exportTour(${i})">Navigation öffnen</button></p>`).join("")}</div>${nav()}</div>`}
function generateRoute(){const title=document.getElementById("tourTitle").value.trim()||"Neue Tour",duration=document.getElementById("tourDuration").value.trim()||"1 Stunde",via=document.getElementById("tourVia").value.trim()||"Noch keine Orte",style=document.getElementById("tourStyle").value;const places=via.split(/,|·|\n/).map(x=>x.trim()).filter(Boolean);const route=["Clubhaus",...places,"Clubhaus"].join(" → ");state.tours.unshift({title,duration,via,style,riders:[],route});save();alert("Routenvorschlag gespeichert.");tours()}
function joinTour(i){const u=state.users[state.current],name=u.name;state.tours[i].riders=state.tours[i].riders||[];if(!state.tours[i].riders.includes(name)){state.tours[i].riders.push(name);u.points+=10}save();tours()}
function exportTour(i){const q=encodeURIComponent((state.tours[i].route||state.tours[i].via).replaceAll("→"," "));window.open(`https://www.google.com/maps/search/?api=1&query=${q}`,"_blank")}
function events(){app.innerHTML=`<div class="app"><h2>Veranstaltungen</h2>${state.users[state.current].role==="admin"?`<div class="card gold"><h3>Event erstellen</h3><input id="evTitle" placeholder="Titel"><input id="evDate" placeholder="Datum/Uhrzeit"><input id="evPlace" placeholder="Ort"><button onclick="createEvent()">Event speichern</button></div>`:""}${state.events.map((e,i)=>`<div class="card"><h3>${e.title}</h3><p>${e.date}<br><span class="small">${e.place}</span></p><p class="small">Zusagen: ${(e.rsvp||[]).join(", ")||"keine"}</p><button onclick="rsvp(${i})">Ich bin dabei</button></div>`).join("")}${nav()}</div>`}
function createEvent(){const title=document.getElementById("evTitle").value.trim(),date=document.getElementById("evDate").value.trim(),place=document.getElementById("evPlace").value.trim();if(!title)return alert("Titel eingeben.");state.events.unshift({title,date,place,rsvp:[]});save();events()}
function rsvp(i){const u=state.users[state.current],name=u.name;state.events[i].rsvp=state.events[i].rsvp||[];if(!state.events[i].rsvp.includes(name)){state.events[i].rsvp.push(name);u.points+=5}save();events()}
function profile(){const u=state.users[state.current];app.innerHTML=`<div class="app"><h2>Profil & Mitgliedsausweis</h2><div class="idcard"><div class="member"><div class="avatar">🏍️</div><div><h3>${u.name}</h3><span class="badge">${u.memberNo}</span></div></div><p>Mitglied seit ${u.joined}</p><p><b>${u.bike}</b></p><p class="stat">${u.points} Clubpunkte</p></div><div class="card"><h3>Rangliste</h3>${leaderboard()}</div><div class="card"><h3>Garage bearbeiten</h3><input id="bike" value="${u.bike}"><button onclick="state.users[state.current].bike=document.getElementById('bike').value;save();profile()">Speichern</button></div><button class="secondary" onclick="state.current=null;save();loginScreen()">Abmelden</button>${nav()}</div>`}
function leaderboard(){return state.members.slice().sort((a,b)=>(state.users[b].points||0)-(state.users[a].points||0)).map((m,i)=>`<p class="row"><span>${i+1}. ${state.users[m].name}</span><b>${state.users[m].points||0}</b></p>`).join("")}
function install(){app.innerHTML=`<div class="app"><h2>QR & Installation</h2><div class="card gold"><h3>QR-Code fürs Clubhaus</h3><div class="qr">${Array.from({length:49}).map(()=>"<span></span>").join("")}</div><p class="small">Demo-QR: In der Live-Version wird daraus der echte Link zur App.</p></div>${nav()}</div>`}
function admin(){app.innerHTML=`<div class="app"><h2>Adminbereich</h2><div class="tabs four"><button class="${state.adminTab==='stats'?'active':''}" onclick="state.adminTab='stats';admin()">Stats</button><button class="${state.adminTab==='money'?'active':''}" onclick="state.adminTab='money';admin()">Geld</button><button class="${state.adminTab==='stock'?'active':''}" onclick="state.adminTab='stock';admin()">Lager</button><button class="${state.adminTab==='members'?'active':''}" onclick="state.adminTab='members';admin()">Mitglieder</button></div>${state.adminTab==='stock'?adminStock():state.adminTab==='members'?adminMembers():state.adminTab==='money'?adminMoney():adminStats()}${nav()}</div>`}
function adminStats(){const total=Object.values(state.users).reduce((s,u)=>s+(u.balance||0),0),sold=state.drinks.reduce((s,d)=>s+(d.sold||0),0),revenue=state.ledger.filter(l=>l.type==="Getränk").reduce((s,l)=>s+Math.abs(l.amount),0);return `<div class="grid"><div class="tile"><b>Guthaben</b><div class="stat">${euro(total)}</div></div><div class="tile"><b>Verkauft</b><div class="stat">${sold}</div></div><div class="tile"><b>Umsatz</b><div class="stat">${euro(revenue)}</div></div><div class="tile"><b>Anfragen</b><div class="stat">${state.topupRequests.filter(r=>r.status==="offen").length}</div></div></div><div class="card gold"><h3>Export</h3><button onclick="showExport()">Daten anzeigen/exportieren</button><div id="exportBox"></div></div><div class="card"><h3>Kassenabschluss</h3><button onclick="cashClose()">Abschluss speichern</button></div>`}
function showExport(){document.getElementById("exportBox").innerHTML=`<pre>${JSON.stringify({users:state.users,drinks:state.drinks,ledger:state.ledger,tours:state.tours,events:state.events},null,2)}</pre>`}
function cashClose(){const sold=state.drinks.reduce((s,d)=>s+(d.sold||0),0),revenue=state.ledger.filter(l=>l.type==="Getränk").reduce((s,l)=>s+Math.abs(l.amount),0);state.cashClosings.unshift({time:now(),sold,revenue});save();admin()}
function adminMoney(){const total=Object.values(state.users).reduce((s,u)=>s+(u.balance||0),0);return `<div class="card gold"><h3>Guthaben im Umlauf</h3><div class="balance">${euro(total)}</div><select id="member">${state.members.map(m=>`<option value="${m}">${state.users[m].name}</option>`).join("")}</select><input id="amount" type="number" step="0.01" placeholder="Betrag"><button onclick="addBalance()">Direkt freigeben</button></div><div class="card"><h3>Offene Guthaben-Anfragen</h3>${state.topupRequests.filter(r=>r.status==="offen").map((r,i)=>`<p class="msg"><b>${r.name}</b> · ${euro(r.amount)}<br><span class="small">${r.time}</span><br><button onclick="approveTopup(${i})">Freigeben</button></p>`).join("")||"<p class='small'>Keine offenen Anfragen.</p>"}</div><div class="card"><h3>Protokoll</h3>${state.ledger.slice(0,12).map(l=>`<p class="msg"><b>${l.type}</b> · ${l.member} · ${euro(l.amount)}<br><span class="small">${l.time}</span></p>`).join("")||"<p class='small'>Noch kein Protokoll.</p>"}</div>`}
function approveTopup(openIndex){const open=state.topupRequests.filter(r=>r.status==="offen");const req=open[openIndex];req.status="freigegeben";state.users[req.member].balance=+(state.users[req.member].balance+req.amount).toFixed(2);state.ledger.unshift({type:"Einzahlung",member:req.name,amount:req.amount,time:now(),admin:state.users[state.current].name});save();admin()}
function addBalance(){const m=document.getElementById("member").value,amount=Number(document.getElementById("amount").value||0);if(amount<=0)return alert("Bitte Betrag eingeben.");state.users[m].balance=+(state.users[m].balance+amount).toFixed(2);state.ledger.unshift({type:"Einzahlung",member:state.users[m].name,amount,time:now(),admin:state.users[state.current].name});save();admin()}
function adminStock(){const low=state.drinks.filter(d=>d.stock<d.min);return `<div class="card"><h3>Einkaufsliste</h3>${low.map(d=>`<p class="msg"><b>${d.name}</b><br>Bestand ${d.stock}, Mindestbestand ${d.min}<br>Empfehlung: ${Math.max(d.min*2-d.stock,0)} nachbestellen</p>`).join("")||`<p class="ok">Keine Nachbestellung nötig.</p>`}</div><div class="card"><h3>Bestand erhöhen</h3><select id="drink">${state.drinks.map((d,i)=>`<option value="${i}">${d.name}</option>`).join("")}</select><input id="stockAmount" type="number" placeholder="Menge"><button onclick="addStock()">Bestand hinzufügen</button></div>`}
function addStock(){const i=Number(document.getElementById("drink").value),amount=Number(document.getElementById("stockAmount").value||0);if(amount<=0)return alert("Bitte Menge eingeben.");state.drinks[i].stock+=amount;save();admin()}
function adminMembers(){return `<div class="card gold"><h3>Mitglied anlegen</h3><input id="newUser" placeholder="Benutzername"><input id="newName" placeholder="Name"><input id="newPass" placeholder="Start-Passwort"><button onclick="createMember()">Mitglied anlegen</button></div><div class="card"><h3>Mitglieder & Rangliste</h3>${leaderboard()}</div>`}
function createMember(){const id=document.getElementById("newUser").value.trim().toLowerCase(),name=document.getElementById("newName").value.trim(),pass=document.getElementById("newPass").value.trim()||"club123";if(!id||!name)return alert("Benutzername und Name eingeben.");if(state.users[id])return alert("Benutzer existiert schon.");const nr="AI-"+String(state.members.length+1).padStart(3,"0");state.users[id]={password:pass,name,role:"member",balance:0,bookings:[],bike:"Noch kein Motorrad",memberNo:nr,joined:new Date().getFullYear(),active:true,points:0};state.members.push(id);save();admin()}
loginScreen();
