
const state={current:null,page:"home",users:{florian:{password:"club123",name:"Florian",role:"member",balance:24.50,bookings:[],bike:"Harley-Davidson Street Bob"},admin:{password:"admin123",name:"Admin",role:"admin",balance:0,bookings:[],bike:"Ad Infinitum Verwaltung"}},drinks:[{name:"Augustiner",price:2,stock:89,emoji:"🍺"},{name:"Chiemseer",price:2,stock:76,emoji:"🍺"},{name:"Monster Energy",price:2.5,stock:34,emoji:"🟢"},{name:"Red Bull",price:2,stock:41,emoji:"🔴"},{name:"Kaffee",price:2,stock:28,emoji:"☕"},{name:"Wasser",price:1,stock:53,emoji:"💧"},{name:"Cola 250 ml",price:1.5,stock:63,emoji:"🥤"},{name:"Fanta 250 ml",price:1.5,stock:44,emoji:"🥤"},{name:"Sprite 250 ml",price:1.5,stock:38,emoji:"🥤"}],chat:[{from:"Admin",text:"Willkommen im Ad Infinitum Club-Chat.",time:"Heute 18:00"},{from:"Florian",text:"Wer ist heute Abend im Clubhaus?",time:"Heute 18:22"}],events:[{title:"Clubabend",date:"Samstag, 19:00 Uhr",place:"Clubhaus"},{title:"Saison-Ausfahrt",date:"Sonntag, 10:00 Uhr",place:"Treffpunkt Clubhaus"}]};
const app=document.getElementById("app");const euro=n=>Number(n).toLocaleString("de-DE",{style:"currency",currency:"EUR"});
function hero(){return `<div class="hero"><div class="infinity"></div><h1>AD INFINITUM</h1><p>ClubApp · Cash · Chat · Touren</p></div>`}
function loginScreen(msg=""){app.innerHTML=`<div class="app">${hero()}<div class="card gold"><h2>Anmelden</h2>${msg?`<p class="warn">${msg}</p>`:""}<input id="username" placeholder="Benutzername"><input id="password" placeholder="Passwort" type="password"><button onclick="login()">Einloggen</button><p class="small">Demo: florian / club123 · admin / admin123</p></div></div>`}
function login(){const u=document.getElementById("username").value.trim().toLowerCase();const p=document.getElementById("password").value;if(state.users[u]&&state.users[u].password===p){state.current=u;state.page="home";render()}else loginScreen("Benutzername oder Passwort falsch.")}
function nav(){const admin=state.users[state.current].role==="admin";const items=[["home","🏠","Start"],["cash","🍺","Cash"],["chat","💬","Chat"],["tours","🗺️","Touren"],[admin?"admin":"profile",admin?"👑":"👤",admin?"Admin":"Profil"]];return `<div class="nav">${items.map(i=>`<button class="${state.page===i[0]?'active':''}" onclick="state.page='${i[0]}';render()">${i[1]}<br>${i[2]}</button>`).join("")}</div>`}
function render(){if(!state.current)return loginScreen();if(state.page==="cash")return cash();if(state.page==="chat")return chat();if(state.page==="tours")return tours();if(state.page==="admin")return admin();if(state.page==="profile")return profile();return home()}
function home(){const u=state.users[state.current];app.innerHTML=`<div class="app">${hero()}<div class="card gold"><h2>Hallo ${u.name} 👋</h2><span class="badge">Mitglied · Ad Infinitum</span><p>Dein Guthaben</p><div class="balance">${euro(u.balance)}</div>${u.balance<5?`<p class="warn">Bitte bald Guthaben aufladen.</p>`:`<p class="ok">Guthaben aktiv</p>`}</div><div class="grid"><div class="tile" onclick="state.page='cash';render()">🍺<b>Getränke</b><span class="small">Direkt buchen</span></div><div class="tile" onclick="state.page='chat';render()">💬<b>Club-Chat</b><span class="small">${state.chat.length} Nachrichten</span></div><div class="tile" onclick="state.page='tours';render()">🗺️<b>Touren</b><span class="small">Route planen</span></div><div class="tile" onclick="state.page='profile';render()">🏍️<b>Garage</b><span class="small">${u.bike}</span></div></div><div class="card"><h3>Nächster Termin</h3><b>${state.events[0].title}</b><br><span class="small">${state.events[0].date} · ${state.events[0].place}</span></div>${nav()}</div>`}
function cash(){const u=state.users[state.current];app.innerHTML=`<div class="app"><h2>ClubCash</h2><div class="card gold"><p>Guthaben</p><div class="balance">${euro(u.balance)}</div></div>${state.drinks.map((d,i)=>`<div class="card drink"><div class="emoji">${d.emoji}</div><div class="info"><b>${d.name}</b><br><span style="color:var(--gold)">${euro(d.price)}</span> <span class="small">· Bestand: ${d.stock}</span></div><button onclick="buy(${i})">+</button></div>`).join("")}<div class="card"><h3>Meine letzten Buchungen</h3>${u.bookings.length?u.bookings.slice(0,4).map(b=>`<p class="msg"><b>${b.drink}</b> · ${euro(b.price)}<br><span class="small">${b.time}</span></p>`).join(""):`<p class="small">Noch keine Buchungen.</p>`}</div>${nav()}</div>`}
function buy(i){const u=state.users[state.current],d=state.drinks[i];if(d.stock<=0)return alert("Nicht auf Lager.");if(u.balance<d.price)return alert("Nicht genügend Guthaben.");d.stock--;u.balance=+(u.balance-d.price).toFixed(2);u.bookings.unshift({drink:d.name,price:d.price,time:new Date().toLocaleString("de-DE")});alert(`${d.name} gebucht. Neues Guthaben: ${euro(u.balance)}`);cash()}
function chat(){app.innerHTML=`<div class="app"><h2>Club-Chat</h2><div class="card gold"><b>Allgemeiner Chat</b><p class="small">Nur eingeloggte Mitglieder von Ad Infinitum.</p></div>${state.chat.map(m=>`<div class="card"><b>${m.from}</b><br><p>${m.text}</p><span class="small">${m.time}</span></div>`).join("")}<div class="card"><input id="chatText" placeholder="Nachricht schreiben..."><button onclick="sendChat()">Senden</button></div><div class="card"><h3>Admin-Ankündigungen</h3><p class="msg"><b>Vorstand:</b> Samstag Clubabend ab 19:00 Uhr.</p></div>${nav()}</div>`}
function sendChat(){const text=document.getElementById("chatText").value.trim();if(!text)return;state.chat.push({from:state.users[state.current].name,text,time:"Gerade eben"});chat()}
function tours(){app.innerHTML=`<div class="app"><h2>Tourenplaner</h2><div class="mapbox">🗺️ Kartenbereich<br><span class="small">Später mit echter Route über Google Maps / OpenRouteService</span></div><div class="card gold"><h3>Route erstellen</h3><input placeholder="Startpunkt, z. B. Clubhaus"><input placeholder="Fahrzeit, z. B. 1 Stunde"><textarea rows="3" placeholder="Über welche Städte? z. B. Rosenheim, Bad Tölz, Tegernsee"></textarea><select><option>Kurvig & landschaftlich</option><option>Schnellste Route</option><option>Rundtour</option></select><button onclick="alert('In Version 0.3 wird daraus eine echte Tour gespeichert.')">Route vorbereiten</button></div><div class="card"><h3>Geplante Touren</h3><p class="msg"><b>Saison-Ausfahrt</b><br><span class="small">Sonntag · 10:00 Uhr · Treffpunkt Clubhaus</span></p></div>${nav()}</div>`}
function profile(){const u=state.users[state.current];app.innerHTML=`<div class="app"><h2>Profil & Garage</h2><div class="card gold"><h3>${u.name}</h3><p>Motorrad</p><b>${u.bike}</b></div><div class="card"><h3>Datenschutz</h3><p class="small">Mitglieder sehen nur ihre eigenen Buchungen und ihr eigenes Guthaben. Andere Mitgliederdaten bleiben verborgen.</p><button class="secondary" onclick="state.current=null;loginScreen()">Abmelden</button></div>${nav()}</div>`}
function admin(){const total=Object.values(state.users).reduce((s,u)=>s+u.balance,0);const low=state.drinks.filter(d=>d.stock<30);app.innerHTML=`<div class="app"><h2>Adminbereich</h2><div class="grid"><div class="tile"><b>Mitglieder</b><div class="balance">25</div></div><div class="tile"><b>Guthaben</b><div class="balance">${euro(total)}</div></div></div><div class="card gold"><h3>Guthaben freigeben</h3><p>Florian hat 20,00 € bar/Überweisung gezahlt.</p><button onclick="state.users.florian.balance+=20;alert('20 € freigegeben.');admin()">Freigeben</button></div><div class="card"><h3>Lagerwarnung</h3>${low.length?low.map(d=>`<p class="warn">${d.name}: nur ${d.stock} Stück</p>`).join(""):`<p class="ok">Alle Bestände okay.</p>`}</div><div class="card"><h3>Getränke & Bestand</h3>${state.drinks.map(d=>`<div class="row"><span>${d.name}</span><b>${d.stock}</b></div>`).join("<hr style='border-color:#222'>")}</div>${nav()}</div>`}
loginScreen();
