import express from 'express';
import cors from 'cors';
import dotenv from 'dotenv';
import authRoutes from './routes/auth.js';
import drinkRoutes from './routes/drinks.js';
import adminRoutes from './routes/admin.js';
dotenv.config();
const app=express();
app.use(cors({origin:process.env.FRONTEND_ORIGIN||'http://localhost:5173'}));
app.use(express.json());
app.get('/',(req,res)=>res.json({app:'Ad Infinitum ClubApp API',version:'0.4',status:'online'}));
app.use('/api/auth',authRoutes);
app.use('/api/drinks',drinkRoutes);
app.use('/api/admin',adminRoutes);
app.listen(process.env.PORT||4000,()=>console.log('API läuft auf Port '+(process.env.PORT||4000)));
