import express from 'express';
import cors from 'cors';
import dotenv from 'dotenv';
import auth from './routes/auth.js';
import drinks from './routes/drinks.js';
import topups from './routes/topups.js';
import admin from './routes/admin.js';
dotenv.config();
const app=express();
app.use(cors({origin:process.env.FRONTEND_ORIGIN||'http://localhost:5173'}));
app.use(express.json());
app.get('/',(req,res)=>res.json({app:'Ad Infinitum API',version:'0.5'}));
app.use('/api/auth',auth);
app.use('/api/drinks',drinks);
app.use('/api/topups',topups);
app.use('/api/admin',admin);
app.listen(process.env.PORT||4000,()=>console.log('API gestartet'));
